### ISSUE TITLE
problem using extension

### ISSUE THREAD

**Issue by resistorsoftware** [romul/spree-solr-search#3]
I am running Spree 0.11.0 gem. I have installed spree-solr-search as an extension and copied the config to RAILS_ROOT/config. I also installed the recommended jetty-solr and started that process using the provided rake commands. I then logged into the console and tried a simple product search.

Using Product.keywords("foobaz") returns an error:

NoMethodError: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.map
    from /home/dlazar/workspace/ct/vendor/extensions/solr_search/lib/spree/search/solr.rb:7:in `get_products_conditions_for'
    from /usr/lib/ruby/gems/1.8/gems/spree-0.11.0/lib/scopes/product.rb:56

But using Product.search() works and returns an ActsAsSolr object with results.

Am I doing something wrong with how I've set things up to have the Product.keywords() method not work or is this something to do with Spree?

Thanks! I really hope to be able to figure out how to point search at Option Values since that is the best way to find relevant Products for my store.

**Comment by romul** [comment]
You should avoid call `keywords` scope directly. But if you want to do this, then you should take a look at how it used in Spree search mechanism: http://github.com/railsdog/spree/blob/0-11-stable/lib/spree/search.rb#L15

**Comment by resistorsoftware** [comment]
Ok... Thanks...

Can I ask one more question! My products have specific option types. I have assigned many option values to my Products. I have one which happens to be size. I see in your extenstion you coded up a facet for size. When I run a simple search for Products and I get back an ActsAsSolr object, I see the docs array is populated with some results, But I never see the facets? How can I see the facets during script/console tests? Sorry for the newb questions!

**Comment by romul** [comment]
> a simple search for Products

What are you mean? There is code example?

P.S. Do not try to reinvent the wheel, just use as is (without console) to start.

**Comment by resistorsoftware** [comment]
I have not seen any code examples for search.. the main Spree docs talk a lot about facets and search API, but without any code examples of how it all works. I use script/console a lot, and almost never the Spree codebase... so I am curious how to test out search at the command level... 

Product.search("foo") returns an ActsAsSolr object, but it is not really too helpful... I see nothing about facets... no option values on size, color are picked up..etc... so I am looking to learn if I am even installed correctly... seems like I am not getting all the search results I expect... so any snippets of code stressing out the search would be appreciated.

**Comment by romul** [comment]
> I have not seen any code examples for search.. the main Spree docs talk a lot about facets and search API, but without any code examples of how it all works.

I mean your code examples. Search API works out of the box without any additional code. If you want know in details how it works take the time to study the code of Spree::Search module and Spree::Search::Base, Spree::Search::Solr classes.

> so I am curious how to test out search at the command level...

Nohow, needed HTTP-request for correct work, or emulation of request.

> Product.search("foo") returns an ActsAsSolr object

Why you try to use this? Such use does not fit into the Spree. spree-solr-search works only in the Spree.

**Comment by resistorsoftware** [comment]
No matter what Romul, Spree is nothing more than a collection of objects and their methods. I need to know what is going on to make Spree work for my store. I cannot just type something into the search box, hit the search controller and hope it all works. I want to know how to customize SEARCH  to find my Products!! I have something like 500 Products and 24000 option values assigned to them... I need to search those option values... and hoping it just works is not going to help me... nonetheless, thanks for your communications. I will take your advice and try playing with the Search API to learn more.

I would like to know more about how Facets work... so perhaps you could point me to the best example you know of for their use?

Thanks

**Comment by romul** [comment]
> I cannot just type something into the search box, hit the search controller and hope it all works. 

Why just hope? You can test this with integrational tests. Try cucumber or selenium.

You can emulate Solr part of search proccess in console:

```
Spree::Config.searcher.prepare({:per_page => 10, :page => 1})
Spree::Config.searcher.get_products_conditions_for("query")
# after this you can access search results via:
Spree::Config.searcher.products 
Spree::Config.searcher.facets
Spree::Config.searcher.suggest 
```

But it will be just emulation, without real request context.

> so perhaps you could point me to the best example you know of for their use?

I'm already pointed to needed classes above.

**Comment by paulcc** [comment]
And to see how to index options of variants, read http://spreecommerce.com/documentation/searching.html#how-solristiedto-spre

Best example? Romul's code in Spree!

**Comment by resistorsoftware** [comment]
I will take the code snippets above for a spin. One thing is not clear to me. In tests so far. As an explanation, I have 300 Products. Each has option values. Let us assume some have values set to some code:  "215/R45", and that is a size. At the moment, I cannot use the Search to find the Variants with this size setting. I would love to get an Array with say 43 Variants, that all had that setting. That would be awesome. 

The only way I managed to do it, was to create my own SQL finder, and inject that into a custom controller. I like the search idea better though, because not only do I have size, but also about eight other option values per Product that I would like to trigger on. For example, I have a quality setting: could be 200 AA, or 320 AA A, etc. If someone searches for "200 AA", I would love to get an Array of 77 Variants... that I could then present... 

Wow.. this is interesting!! Thanks for the tips getting started on all this. I think I am making some progress.

**Comment by romul** [comment]
Atm search by option value will search this option value inside variants, but will return array of products as result.

**Comment by greengrass** [comment]
Hi Romul, do you have any snippets on how to displaying a side bar, say you search  watches, the result search would display related taxons and a related side bar with associated variants like gold, sliver (watches)  in text links, I know its rending it via facet , with out your help I could spend a few weeks and not get anywhere which has happened a lot, I appreciate your help, am a novice maybe 8 and 1/2 years away from becoming a pro lol, P:S could you paste a snippet if you can because I might not understand reading up the text , thank Brian

**Comment by romul** [comment]
@greengrass To display filter by facets you can use:
https://github.com/romul/spree-solr-search/blob/master/app/views/products/_facets.html.erb
just put `<%= render 'products/facets' %>` to desired place.

**Comment by greengrass** [comment]
Hi I have this problem below when I try run rake solr:start RAILS_ENV=production --trace, I cd /var/www/passenger/jetty-solr, although solr starts fine using java -jar start.jar and I can go to the admin http://ip:8983/solr/admin, also when I search say keyword rolex in my search box I get no products found as in a 404 return, 

Q1,  if I can rake solr:reindex and I search keyword rolex should i get product returns with given keywords should products exist in my database.
Q2, do I need to write a new search keyword scope, if so I have spent weeks researching scopes, I cant hack anything together, its driving me insane, also I tried <%= render 'products/facets' %> its renders nothing maybe because the indexing dont work. 
Please Please post  some scope code if needed, others wise I will have to give up and be very sad if you cant help us,  thanks Brian 

rake aborted!
no such file to load -- /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/acts_as_solr_reloaded-1.4.0/lib/acts_as_solr/tasks/database.rake
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load_without_new_constant_marking'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/acts_as_solr_reloaded-1.4.0/lib/acts_as_solr/tasks.rb:8
/opt/ruby-enterprise/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
/opt/ruby-enterprise/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
/var/www/website/releases/20111608141430/vendor/extensions/solr_search/lib/tasks/acts_as_solr.rake:2
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load_without_new_constant_marking'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load'
/var/www/website/releases/20111608141430/lib/tasks/extensions.rake:234
/var/www/website/releases/20111608141430/lib/tasks/extensions.rake:234:in`each'
/var/www/website/releases/20111608141430/lib/tasks/extensions.rake:234
/var/www/website/releases/20111608141430/lib/tasks/extensions.rake:233:in `each'
/var/www/website/releases/20111608141430/lib/tasks/extensions.rake:233
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load_without_new_constant_marking'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/tasks/rails.rb:9
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/tasks/rails.rb:9:in`each'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/tasks/rails.rb:9
/opt/ruby-enterprise/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/opt/ruby-enterprise/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
/var/www/website/releases/20111608141430/Rakefile:7
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in`load_rakefile'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:82:in`load_rakefile'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:81:in`load_rakefile'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `run'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.9.2.2/bin/rake:33
/opt/ruby-enterprise/bin/rake:19:in`load'
/opt/ruby-enterprise/bin/rake:19
